services:
  web:
    image: ghcr.io/kweonsikyung/daengglejeju:latest
    platform: linux/amd64
    container_name: daengglejeju-web
    ports:
      - "3000:3000"
    env_file:
      - ../apps/web/.env.local
    restart: unless-stopped
