apiVersion: apps/v1
kind: Deployment
metadata:
  name: daengglejeju-web
  labels:
    app: daengglejeju-web
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: daengglejeju-web
  template:
    metadata:
      labels:
        app: daengglejeju-web
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: web
          image: ghcr.io/kweonsikyung/daengglejeju:sha-a619655c9517e4d3bde247d3470206845444d1c1
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "3000"
            - name: HOSTNAME
              value: "0.0.0.0"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
